### ISSUE TITLE
Project Bluebell: time for a site redesign!

### ISSUE THREAD

**Issue by alexwlchan** [alexwlchan/alexwlchan.net#741]
This is a big ticket to cover a moderate redesign of the site and its content. Overall goals:

* Incorporate TILs as a top-level idea
* Simplify the number of pages I need to maintain and manage (`/projects/` is very out-of-date!)
* Simplify some of the codebase and build process
* Make the build faster to run locally

I'll put details in individual PRs linked to this issue.

- [x] Fix the page width bug
- [x] Rip out the "subscribe" component
- [x] Fix the CSS cache-busting
- [x] Add the TILs and their RSS feed
- [x] Swap out the primary font
- [x] Tweak the link styles
- [x] Change the top nav
- [x] ~~Create an articles collection~~
- [x] Bin the projects page
- [x] Move across all the old TILs
- [x] Get rid of per-year indexes
- [x] Add a "fun stuff" page
- [ ] Fold in "inclusive events"
- [x] Every page should be in a nav section
- [x] Run in macOS Ruby (#760)
- [x] Go back to _posts, actually (#765)
- [x] Bump the Nokogiri version (#769)

**Comment by alexwlchan** [comment]
For at least some of these changes, I want to make sure I'm not changing the output of the site. I've written a short Python script that compares two copies of the site and checks they're byte-for-byte identical:

```python
import pathlib
import filecmp

import tqdm


def get_file_paths_under(root=".", *, suffix=""):
    """
    Generates the absolute paths to every matching file under ``root``.
    """
    root = pathlib.Path(root)

    if root.exists() and not root.is_dir():
        raise ValueError(f"Cannot find files under file: {root!r}")

    if not root.is_dir():
        raise FileNotFoundError(root)

    for dirpath, _, filenames in root.walk():
        for f in filenames:
            p = dirpath / f

            if p.is_file() and f.lower().endswith(suffix):
                yield p


for p in tqdm.tqdm(list(get_file_paths_under("_site.amber"))):
    new_p = pathlib.Path(str(p).replace("_site.amber", "_site"))

    if not new_p.exists():
        print(p)
        continue

    if not filecmp.cmp(p, new_p, shallow=False):
        print(p)

for p in tqdm.tqdm(list(get_file_paths_under("_site"))):
    old_p = pathlib.Path(str(p).replace("_site", "_site.amber"))

    if not old_p.exists():
        print(p)
        continue
```

**Comment by alexwlchan** [comment]
One thing I've discovered: the built-in `smartify` filter is pretty slow! I can make the site a lot faster by using that more judiciously (and maybe caching the output later?).

**Comment by alexwlchan** [comment]
I'm starting to simplify my CSS setup (see more notes in #743).

As a brief benchmark, the size of my current `style.css` file is 16,888 bytes.

**Comment by alexwlchan** [comment]
I'm going to close this as done – I got enough of the cosmetic improvements that I wanted to do under this project done, and I wrote two blog posts about them:

https://alexwlchan.net/2024/not-all-posts/
https://alexwlchan.net/2025/style-updates-2025/
